### PR TITLE
Include the pump filter entity as switch

### PR DESCRIPTION
**Pull request by FRight80**
This will include the pump filter entity as a switch, it is based on your code for the lights, just on the filtration entity instead. I've added it as a switch entity so separate from the light.

### CODE REVIEW

**Comment by Hans1205** [comment]
I have integrated the changes in my system (Bayrol Salt Relax Pro) and it works! Great! I've been looking for this for a long time!

Can this be extended?
At the moment you can only use the Filtration switch if the filtration is set to "Manual". I usually run the filtration in "Smart" mode. However, my actual goal is to operate the pool heat pump with PV overproduction. This already works, but of course the heat pump only runs when the filtration is also running, so in this case I would like to switch from "Smart" to "Manual" and switch on the pump, which would also be ideal with a choice of speed (slow, medium, fast). If the automation then switches the heat pump off again, this should then be switched back to Smart if possible. Would that be possible?

**Review by Hans1205 — APPROVED** [review]
Works if Filtration mode is "Manual". Great!

**Comment by FRight80** [comment]
Unfortunately I haven't seen API documentation, so a bit of trial and error from my side. There is a "mode" parameter in the filtration entity output which I think controls the auto/manual mode. I think it can be set when turning on/off. Will play around with it next weekend. I am getting some authorization errors when trying to toggle the lights/filter after some time. Seems like the token is not getting properly refreshed... a restart fixes it - have you seen the same?

**Comment by fdebrus** [comment]
Hello, I’ve the same behavior « token refresh «  in my fork. Not sure being related to token as it surfaced last week. Been using the integration for some months without issue. Was a timeout implemented at server side ? Getting 401, it could be catched to re-trigger authentification. 

I’ve implemented more switches and controls, feel free to copy/paste :) 

as time allow, will deep dive on the 401

**Comment by Hans1205** [comment]
Since today I also get the authentication errors. What do I have to do to re-authenticate?

You write about other switches and controls ... Where can I find them?

**Pull request merged**
